import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Permission from 'App/Models/Permission'

export default class extends BaseSeeder {
    public async run() {
        // Write your database queries inside the run method
        await Permission.createMany([
            {
                id: 1,
                role_id: 1,
                module_id: 1,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 2,
                role_id: 1,
                module_id: 2,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 3,
                role_id: 1,
                module_id: 3,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 4,
                role_id: 1,
                module_id: 4,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 5,
                role_id: 1,
                module_id: 5,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 6,
                role_id: 1,
                module_id: 6,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 7,
                role_id: 1,
                module_id: 7,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 8,
                role_id: 1,
                module_id: 8,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 9,
                role_id: 1,
                module_id: 9,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 10,
                role_id: 1,
                module_id: 10,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 11,
                role_id: 1,
                module_id: 11,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 12,
                role_id: 1,
                module_id: 12,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 13,
                role_id: 1,
                module_id: 13,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 14,
                role_id: 1,
                module_id: 14,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 15,
                role_id: 1,
                module_id: 15,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 16,
                role_id: 1,
                module_id: 16,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 17,
                role_id: 1,
                module_id: 17,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 18,
                role_id: 1,
                module_id: 18,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 19,
                role_id: 1,
                module_id: 19,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 20,
                role_id: 1,
                module_id: 20,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 21,
                role_id: 1,
                module_id: 21,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
            {
                id: 22,
                role_id: 1,
                module_id: 22,
                is_read: true,
                is_write: true,
                is_delete: true,
                is_update: true,
            },
        ])
    }
}
