const fields = {
  step_1: {
    company_name: '',
    phone: '',
    email: '',
    industry_type: '',
    customer_type: "",
    equipment: '',
    address: '',
    city: '',
    pincode: '',
    state: '',
    image: '',
    account_number: '',
    account_name: '',
    bank_name: '',
    ifsc_code: '',
    cancelled_cheque: '',
    gst_no: '',
    gst_certificate: '',
    is_credit_availed: false,
    credit_net_due_id: "",
    credit_limit: "",
    outstanding_amount: "",
    credit_pan: '',
    credit_bank_statement: '',
    credit_aadhaar: '',
    credit_blank_cheque: '',
    credit_cibil: '',
    sales_executive_id: '',

  },
  step_2: {
    poc_name: '',
    designation: '',
    phone: '',
    email: '',
    image: '',
  },
  step_3: {
    address_1: '',
    address_2: '',
    pincode: '',
    address_type: '',
    city: '',
    state: '',
    phone: '',
    landmark: '',
    location: '',
    customer_poc_id: '',
    fuel_price: "",
    is_fuel_price_checked: false,
  },
};

const rules = {
  step_1: {
    company_name: 'required|min:3|max:20',
    phone: 'required|numeric|digits:10',
    email: 'required|email',
    industry_type: 'required',
    customer_type: "required",
    equipment: 'required',
    address: 'required|max:500',
    city: 'required|alpha',
    pincode: 'required|string|min:6|max:6',
    state: 'required',
    image: 'required',

    // account_number: 'required|numeric',
    // account_name: 'required|min:3|max:20',
    // bank_name: 'required',
    // ifsc_code: 'required',
    // cancelled_cheque: 'required',
    // gst_no: 'required',
    // gst_certificate: 'required',
    sales_executive_id: 'required',
  },
  step_2: {
    poc_name: 'required|max:20',
    designation: 'required|max:20',
    phone: 'required|numeric|digits:10',
    email: 'required|email',

  },
  step_3: {
    address_1: 'required',
    address_type: 'required',
    city: 'required|alpha',
    pincode: 'required|numeric|digits:6',
    state: 'required',
    phone: 'required|numeric|digits:10',
    customer_poc_id: 'required',
  },
};

module.exports = { fields, rules };
